### ISSUE TITLE
Problem when I try to install docker-phpqa on Windows

### ISSUE THREAD

**Issue by lflimeira** [herdphp/docker-phpqa#30]
When I try to install docker-phpqa on windows the following error occurs: 

$ curl -s https://raw.githubusercontent.com/herdphp/docker-phpqa/master/bin/ins
taller.sh | bash
PHPQA installer started ...
Step 1: clonning the repository to /c/Users/LuizFelipe/.phpqa/bin/phpqa.sh
Cloning into 'C:/Users/LuizFelipe/.phpqa'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Step 2: linking phpqa.sh to /usr/local/bin/phpqa ...
ln: failed to create symbolic link ‘/usr/local/bin/phpqa’: No such file or directory
Step 3: applying exec permissions ...
chmod: cannot access ‘/usr/local/bin/phpqa’: No such file or directory
Success! The phpqa command was added to your /usr/local/bin folder and can be used globally.

Note: I already have Docker installed.

**Comment by brunoric** [comment]
Hi @lflimeira, about the permission issue please make sure that your ssh keys and config are not impacting when trying to clone GitHub repositories. Try to clone the repository instead of using the installer, if you have the same issue please refer to [this Github article](https://help.github.com/articles/error-permission-denied-publickey/). If by any reason you are able to clone the repository but not to use the installer from the remote location you can run the installer from the cloned repository with `bash path/to/your/phpqa/repo/bin/installer.sh`.

Please let us know if you solved your problem.

**Comment by lflimeira** [comment]
@brunoric thank you for your answer and attention.

I clone the repository and I tried to run the locally installer, but it gave me the same error:

$ bash bin/installer.sh
PHPQA installer started ...
Step 1: clonning the repository to /c/Users/LuizFelipe/.phpqa/bin/phpqa.sh
Cloning into 'C:/Users/LuizFelipe/.phpqa'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Step 2: linking phpqa.sh to /usr/local/bin/phpqa ...
ln: failed to create symbolic link ‘/usr/local/bin/phpqa’: No such file or directory
Step 3: applying exec permissions ...
chmod: cannot access ‘/usr/local/bin/phpqa’: No such file or directory
Success! The phpqa command was added to your /usr/local/bin folder and can be used globally.

Could it be some problem of permission on Docker?

When I try to run $ phpqa phpt/lflimeira/ it gives me the following error.

bash: phpqa: command not found

**Comment by lflimeira** [comment]
So, my problem can't be solved @brunoric?

**Comment by brunoric** [comment]
Hi @lflimeira,

As I told you before you must have some problem with your Github ssh keys. If you take a look at [phpqa installer](https://github.com/herdphp/docker-phpqa/blob/master/bin/installer.sh) you will see that it basically clones the repo to a default place and symlink it. If you are able to clone it and the installer doesn't something is wrong on your end regarding the keys. Anyway, since you said that you were able to clone you can use the `phpqa` from the repository or if you prefer to create a global link for it. To use the `phpqa` script from your cloned repository just use `bash path/to/your/phpqa/repo/bin/phpqa.sh`.

**Comment by lflimeira** [comment]
@brunoric  thank you so much for your answer and attention. I think that the problem it's me :)

See what's happening:

![image](https://user-images.githubusercontent.com/7549765/29054062-1e20c4e6-7bca-11e7-8591-8d211d8c42b2.png)

**Comment by brunoric** [comment]
Hi @lflimeira,

You are missing the `run` subcommand.

````bash
bash bin/phpqa.sh run phpt/examples
````

I can see that the usage message is also missing it but is just a misleading message and I will send a PR to fix it.

=)

**Comment by jpjoao** [comment]
Regarding the "pulling the latest changes", I've just sent a PR that should make that easier (#32).

In the meanwhile you can manually update your docker images by running the following commands:
```
docker pull herdphp/phpqa:55
docker pull herdphp/phpqa:56
docker pull herdphp/phpqa:70
docker pull herdphp/phpqa:71
docker pull herdphp/phpqa:72
```

Cheers,
João Paulo

**Comment by lflimeira** [comment]
@brunoric e @jpjoao, it worked. Thank you so much. You guys, helped me a lot. :smile:
